### ISSUE TITLE
Placeholder Not working

### ISSUE THREAD

**Issue by ErAshu** [blurryssky/BSCycleThroughView#1]
I am using webImage, but placeholder image is not working there.
   bannerView.placeholderImage = #imageLiteral(resourceName: "Apartments_3")

showing blank in place of placeholder.

**Comment by ErAshu** [comment]
I found the issue, collectionview cell have not assign the placeholder image. Now i assign and its working fine.

**Comment by blurryssky** [comment]
...I was wanted to provide this feature, but I forgot to do it, sorry I'll fix this later.
